<a href="https://colab.research.google.com/github/davillegasm/AP0053-20243/blob/tuplas-loops/Udmy3_Dataframe_From_Dictionary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = {"name": ["Sally", "Jhon", "Kim"], "age": [4, 6 ,7], "gender": ["female", "male", "male"]}

In [ ]:
pd.DataFrame(data)

    name  age  gender
0  Sally    4  female
1   Jhon    6    male
2    Kim    7    male

In [ ]:
pd.DataFrame(data, index = ["Kid1", "Kid2", "Kid3"])

       name  age  gender
Kid1  Sally    4  female
Kid2   Jhon    6    male
Kid3    Kim    7    male